{{- if .Values.nginx.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.nginx.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.nginx.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ template "nginx.fullname" . }}
                port:
                    number: {{ .Values.nginx.service.port }}
  {{- if .Values.nginx.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.nginx.ingress.tls.secretName | quote }}
      hosts:
        - {{ .Values.nginx.host | quote }}
  {{- end }}
{{- end }}
